/**
 * Utility to extract a human-readable error message from a backend API error.
 * Handles the specific formats generated by the Ideagram backend:
 * 1. CamelCase field errors (nonFieldErrors, etc.)
 * 2. Auth 'detail' errors
 * 3. General field validation arrays
 */
export const getErrorMessage = (error: unknown, fallback: string = 'An unexpected error occurred'): string => {
  if (!error) return fallback;

  // Handle Axios response structure
  const axiosError = error as { response?: { data?: Record<string, unknown> }; message?: string };
  const data = axiosError.response?.data;

  if (data) {
    // Priority 1: Auth or System-level 'detail' (Status 401/403/etc.)
    if (data.detail && typeof data.detail === 'string') {
      return data.detail;
    }

    // Priority 2: General validation errors (mapped from snake_case by CamelCaseJSONRenderer)
    if (data.nonFieldErrors) {
      if (Array.isArray(data.nonFieldErrors) && data.nonFieldErrors.length > 0) {
        return data.nonFieldErrors[0];
      }
      if (typeof data.nonFieldErrors === 'string') {
        return data.nonFieldErrors;
      }
    }

    // Priority 3: Field-specific errors (Check for first available error array)
    // We exclude 'code' as it might be an internal identifier (Pattern C)
    const errorKeys = Object.keys(data).filter(key => key !== 'code' && key !== 'detail');
    if (errorKeys.length > 0) {
      const firstKey = errorKeys[0];
      const fieldError = data[firstKey];
      
      if (Array.isArray(fieldError) && fieldError.length > 0) {
        // e.g. { "email": ["Invalid format"] } -> "Email: Invalid format"
        const friendlyKey = firstKey.charAt(0).toUpperCase() + firstKey.slice(1).replace(/([A-Z])/g, ' $1');
        return `${friendlyKey}: ${fieldError[0]}`;
      }
      
      if (typeof fieldError === 'string') {
        return fieldError;
      }
    }
  }

  // Priority 4: Axios-level message (e.g. "Network Error")
  if (axiosError.message && typeof axiosError.message === 'string') {
    return axiosError.message;
  }

  return fallback;
};
